import type { Metadata } from "next";
import { VT323 } from "next/font/google";
import "./globals.css";


const vt323 = VT323({
  variable: "--font-vt323",
  subsets: ["latin"],
  weight: ["400"],
  style: "normal",
});

// Metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${vt323.variable} font-vt323 antialiased min-h-screen bg-black text-gray-100`}>
        {children}
      </body>
    </html>
  );
}
